include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # Enable the following rules to enforce best practices
    # https://dart.dev/tools/linter
    # https://dart.dev/tools/linter#lints
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    avoid_unnecessary_containers: false
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    prefer_const_constructors: true
    prefer_relative_imports: true
    require_trailing_commas: true
# Enable the following rules to enforce best practices    