name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  intl: ^0.20.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true
  assets:
    - .env
